CREATE TABLE "organization" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"inn" VARCHAR(12) NOT NULL UNIQUE,
	"ogrn" VARCHAR(13) NOT NULL UNIQUE,
	"adress" TEXT,
	"phone" VARCHAR(12),
	"email" VARCHAR(255),
	"is_resident" BOOLEAN NOT NULL,
	"is_legal_entity" BOOLEAN NOT NULL,
	"passport_data" VARCHAR(100),
	"foreign_tax_id" VARCHAR(100),
	PRIMARY KEY("id")
);
CREATE INDEX "organization_index_0"
ON "organization" ("inn", "ogrn");

CREATE TABLE "representative" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"organization_id" INTEGER NOT NULL,
	"full_name" VARCHAR(255) NOT NULL,
	"position" VARCHAR(255),
	"phone" VARCHAR(12),
	"email" VARCHAR(255),
	PRIMARY KEY("id")
);
CREATE INDEX "representative_index_0"
ON "representative" ("full_name");

CREATE TABLE "contract" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"organization_id" INTEGER NOT NULL,
	"contract_number" VARCHAR(100) NOT NULL,
	"status" VARCHAR(100) NOT NULL,
	"start_date" DATE,
	"end_date" DATE,
	"payment_amount" DECIMAL(15, 2),
	"currency" VARCHAR(3),
	PRIMARY KEY("id")
);
CREATE INDEX "contract_index_0"
ON "contract" ("contract_number", "organization_id", "status", "end_date");

CREATE TABLE "work" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"contract_id" INTEGER NOT NULL,
	"description" TEXT,
	"status" VARCHAR(100),
	"start_date" DATE,
	"end_date" DATE,
	PRIMARY KEY("id")
);
CREATE INDEX "work_index_0"
ON "work" ("contract_id", "status");

CREATE TABLE "act" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"work_id" INTEGER NOT NULL,
	"cert_number" VARCHAR(100) NOT NULL,
	"issue_date" DATE NOT NULL,
	"status" VARCHAR(100),
	PRIMARY KEY("id")
);
CREATE INDEX "act_index_0"
ON "act" ("work_id", "status");

CREATE TABLE "currency" (
	"code" VARCHAR(3) NOT NULL UNIQUE,
	"name" VARCHAR(100) NOT NULL,
	PRIMARY KEY("code")
);

ALTER TABLE "representative"
ADD FOREIGN KEY("organization_id") REFERENCES "organization"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "contract"
ADD FOREIGN KEY("organization_id") REFERENCES "organization"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "work"
ADD FOREIGN KEY("contract_id") REFERENCES "contract"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "act"
ADD FOREIGN KEY("work_id") REFERENCES "work"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "contract"
ADD FOREIGN KEY("currency") REFERENCES "currency"("code")
ON UPDATE NO ACTION ON DELETE NO ACTION;